{{- range $ingress := .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if contains "." $ingress.host }}
  name: {{ $ingress.host | replace "." "-" }}
  {{- else }}
  name: {{ $ingress.host | replace "." "-" }}-{{ $.Values.domain | replace "." "-" }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: lain-internal
    {{- with $.Values.ingressAnnotations }}
    {{- range $k, $v := $.Values.ingressAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  rules:
    {{- if contains "." $ingress.host }}
    - host: {{ $ingress.host }}
    {{- else }}
    - host: {{ $ingress.host }}.{{ $.Values.domain }}
    {{- end }}
      http:
        paths:
        {{- range $ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $.Values.appname }}-{{ $ingress.deployName }}
              servicePort: 80
        {{- end }}

{{- end }}
